services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['listen_https'] = false
        gitlab_rails['gitlab_https'] = false
        # Enable Container Registry
        registry_external_url 'http://gitlab.example.com:5050'
        registry['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
    ports:
      - '80:80'
      - '2222:22'
      - '5050:5050'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      gitlab-network:
        aliases:
          - gitlab.example.com

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    depends_on:
      gitlab:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
      - ${HOME}/.kube:/root/.kube:ro
      - ${HOME}/.minikube:${HOME}/.minikube:ro
    environment:
      - KUBECONFIG=/root/.kube/config
    networks:
      - gitlab-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

networks:
  gitlab-network:
    driver: bridge